Fixes ocp-indent build
Unibeautify/docker-beautifiers pull request #3
Opened 2017-09-23 22:10 UTC by szeck87

2017-09-23 22:14 UTC, szeck87 commented
This only fixes the build, it still does not run.  Getting error `Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"ocp-indent\": executable file not found in $PATH".`

2017-09-25 01:48 UTC, Glavin001 commented
> This only fixes the build

Please enable for Travis CI now too :) https://github.com/Unibeautify/docker-beautifiers/blob/master/.travis.yml#L13

> it still does not run.

I am not really familiar with `ocp-indent`. Are you interested in researching how to fix this? Once it is fixed, it will be great to merge. Thank you for contributing!

2017-09-25 01:49 UTC, Glavin001 requested changes
> This only fixes the build

Please enable for Travis CI now too :) https://github.com/Unibeautify/docker-beautifiers/blob/master/.travis.yml#L13

> it still does not run.

I am not really familiar with `ocp-indent`. Are you interested in researching how to fix this? Once it is fixed, it will be great to merge. Thank you for contributing!

2017-09-25 15:33 UTC, szeck87 commented
> Are you interested in researching how to fix this?

Yep I'm actively trying to fix it.  I spent quite a bit of time learning ocp-indent trying to fix the Travis build in atom-beautify where ocp-indent kept causing it to exit.  Still trying to learn Docker as I go and resorting to Stack Overflow for a few questions and problems.

> Please enable for Travis CI now too

Whoops sorry, I meant it only fixes the [docker build where it failed](https://hub.docker.com/r/unibeautify/ocp-indent/builds/). Once everything is fixed I'll enable the Travis build in this PR.

2017-09-25 16:25 UTC, szeck87 commented
@Glavin001 updated my master branch, should reflect in the PR

2017-09-25 17:50 UTC, Glavin001 commented
Great! Looks like ocp-indent is working and the others are breaking now 🙄 .

2017-09-25 17:50 UTC, merged

2017-09-25 20:20 UTC, szeck87 commented
Sadly this still isn't working.  The builds in Docker and Travis run without errors, but actual usage (almost) doesn't.  Right now my guess is it doesn't like the -t flag that whalebrew uses when running docker images, no idea why.